version: "3"

services:
  pma:
    labels:
      - traefik.enable=true
      - traefik.http.routers.berthott-pma.rule=Host(`pma.berthott.de`)
      - traefik.http.routers.berthott-pma.tls=true
      - traefik.http.routers.berthott-pma.tls.certresolver=lets-encrypt
      - traefik.http.routers.berthott-pma.middlewares=basic-auth@file

  directus:
    labels:
      - traefik.enable=true
      - traefik.http.routers.directus.rule=Host(`admin.berthott.de`)
      - traefik.http.routers.directus.tls=true
      - traefik.http.routers.directus.tls.certresolver=lets-encrypt
      - traefik.http.services.directus.loadbalancer.server.port=8055

  berthott:
    labels:
      - traefik.enable=true
      - traefik.http.routers.berthott-sieben.rule=Host(`beta.berthott.de`)
      - traefik.http.routers.berthott-sieben.tls=true
      - traefik.http.routers.berthott-sieben.tls.certresolver=lets-encrypt
      - traefik.http.services.berthott-sieben.loadbalancer.server.port=3000
