version: '3'

networks:
  web:
    external: true
  internal:
    external: false

services:
  db:
    image: mysql
    restart: unless-stopped
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./directus/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_DATABASE
      - MYSQL_USER=$DB_USER
      - MYSQL_INITDB_SKIP_TZINFO=true
    networks:
      - internal

  pma:
    image: phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PMA_HOST: db
    networks:
      - web
      - internal

  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - internal

  directus:
    image: directus/directus:10.10.4
    restart: unless-stopped
    volumes:
      - ./directus/uploads:/directus/uploads
      # - ./extensions:/directus/extensions
    depends_on:
      - cache
      - db
    environment:
      KEY: 'cMFzFNq9CxQJFADhsKcrRfGjsSFF6JfPzABRqAnrXWu6tBgeaw'
      SECRET: 'cMFzFNq9CxQJFADhsKcrRfGjsSFF6JfPzABRqAnrXWu6tBgeaw'

      ADMIN_EMAIL:
      ADMIN_PASSWORD:

      DB_CLIENT: 'mysql'
      DB_HOST: 'db'
      DB_PORT: '3306'
      DB_DATABASE:
      DB_USER:
      DB_PASSWORD:
      PUBLIC_URL:

      CACHE_ENABLED: 'true'
      CACHE_AUTO_PURGE: 'true'
      CACHE_STORE: 'redis'
      REDIS: 'redis://redis:6379'

      WEBSOCKETS_ENABLED: true
    networks:
      - internal
      - web

  berthott:
    build:
      context: ./nextjs
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./nextjs/src:/app/src
      - ./nextjs/public:/app/public
    environment:
      NEXT_ENV:
    ports: 
      - 3000:3000
    networks:
      - internal
      - web
    