version: "3"

services:
  pma:
    labels:
      - traefik.enable=true
      - traefik.http.routers.berthott-pma.rule=Host(`berthott-pma.syspons.local`)
      - traefik.http.routers.berthott-pma.tls=true
      - traefik.http.routers.berthott-pma.tls.certresolver=lets-encrypt
      #- traefik.http.routers.berthott-pma.middlewares=basic-auth@file

  directus:
    labels:
      - traefik.enable=true
      - traefik.http.routers.directus.rule=Host(`directus.syspons.local`)
      - traefik.http.routers.directus.tls=true
      - traefik.http.routers.directus.tls.certresolver=lets-encrypt
      #- traefik.http.routers.directus.middlewares=basic-auth@file

  berthott:
    labels:
      - traefik.enable=true
      - traefik.http.routers.berthott.rule=Host(`berthott.syspons.local`)
      - traefik.http.routers.berthott.tls=true
      - traefik.http.routers.berthott.tls.certresolver=lets-encrypt
